version: '3.3'

services:
  mud-game:
    image: mud-game-dungeons-and-dragons
    container_name: mud-game-dungeons-and-dragons
    build:
      context: .
      dockerfile: GameDockerfile
    volumes:
      - ".:/app"
    entrypoint: "tail -f /dev/null"